# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
     config.vm.define "sf-pr11" do |machine|
  # Other configuration options for the VM goes here below this comment
	  machine.vm.provider "virtualbox" do |vb|
    		vb.memory = "2048"
  	  end
	end
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip
      pip3 install psycopg2-binary Django
      touch /home/vagrant/empty_file.txt
   SHELL
end

