Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip python3-psycopg2 python3-django
  SHELL

  config.vm.provision "file", source: "empty_file.txt", destination: "~/empty_file.txt"
end
